name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Or whatever branch you want to trigger deployments from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build # Or `yarn build` if you're using Yarn

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}' # This is the secret you just created
          projectId: 'nucamp-campsie'
          channelId: live # Deploy to the 'live' channel (your main domain)
          target: # Optional: if you have multiple hosting sites in one project
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
